In [1]:
import torch
from d2l import torch as d2l

In [2]:
def corr2d_multi_in(X, K):
    # There are multiple channels in the X,
    # and the channels in the kernel are same
    return sum(d2l.corr2d(X[c], K[c]) for c in range(X.shape[0]))

# # Another implementation
# def corr2d_multi_in(X, K):
#     return sum(d2l.corr2d(x, k) for x, k in zip(X, K))

In [10]:
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
                  [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])

corr2d_multi_in(X, K)

tensor([[ 56.,  72.],
        [104., 120.]])

In [11]:
def corr2d_multi_in_out(X, K):
    return torch.stack([corr2d_multi_in(X, k) for k in K], 0)

In [12]:
K = torch.stack((K, K+1, K+2), 0)
K.shape

torch.Size([3, 2, 2, 2])

In [14]:
corr2d_multi_in_out(X, K)

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])

In [22]:
def corr2d_multi_in_out_1x1(X, K):
    c_i, h, w = X.shape
    c_o = K.shape[0]
    X = X.reshape((c_i, h*w))
    K = K.reshape((c_o, c_i))
    Y = torch.matmul(K, X)
    return Y.reshape((c_o, h, w))

In [23]:
X = torch.normal(0, 1, (3, 3, 3))
K = torch.normal(0, 1, (2, 3, 1, 1))

In [25]:
Y1 = corr2d_multi_in_out_1x1(X, K)
Y1

tensor([[[ 1.0500, -1.8121,  0.6465],
         [-1.2438, -0.9559, -0.0113],
         [-1.1372, -0.3786, -0.3511]],

        [[ 3.2269, -4.1407,  1.1530],
         [-2.3952,  0.2743, -4.9611],
         [-1.6393,  1.4501,  0.6523]]])

In [27]:
Y2 = corr2d_multi_in_out(X, K)
Y2

tensor([[[ 1.0500, -1.8121,  0.6465],
         [-1.2438, -0.9559, -0.0113],
         [-1.1372, -0.3786, -0.3511]],

        [[ 3.2269, -4.1407,  1.1530],
         [-2.3952,  0.2743, -4.9611],
         [-1.6393,  1.4501,  0.6523]]])

In [29]:
torch.abs(Y1 - Y2).sum() < 1e-6

tensor(True)